name = "Seymour"
defaultTargets = ["Seymour"]

[leanOptions]
autoImplicit = false
relaxedAutoImplicit = false
pp.structureInstances = false
pp.numericProj.prod = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.17.0"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"
rev = "1325b44da2cac7abb16b175128e589c780e4cc7e"

[[require]]
name = "«doc-gen4»"
git = "https://github.com/leanprover/doc-gen4"
rev = "b031cb6aa39c6db80532975c43594f247b8d4b51"

[[lean_lib]]
name = "Seymour"
